name: img2zarr
channels:
  - conda-forge
dependencies:
  - astropy                  # FITS + WCS
  - black                    # Code formatting
  - click                    # CLI framework
  - flake8                   # Linting
  - imageio>=2.37               # PNG/JPEG/TIFF reader
  - loguru                   # Structured logging
  - numpy                    # Array operations
  - pandas                   # Metadata handling
  - pillow                      # For pip dependencies
  - pytest                   # Testing
  - pytest-cov              # Coverage testing
  - python>=3.10
  - tqdm                     # nice progress bars
  - zarr>=3.0.0b0           # v3 spec support
